version: "3.0"
services:

  flask-factory:
    image: your-registry/your-namespace/flask-factory
    restart: always
    # There are two main methods to make the web to be public.
    # The first one is expose the port like below.
    # The second one is using nignx to access it through the internal docker networks.
    # So that it will be safer and configured easily with load balance.
    volumes:
      - ./:/app
    networks:
      back:
        aliases:
          - flask-factory
        ipv4_address: 192.168.2.99

  mysql:
    image: mysql
    restart: always
    volumes:
      # You'd better change it to be a safe and fixed place outside of this project.
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/vat/log/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_factory
    networks:
      back:
        aliases:
          - mysql

  mongo:
    image: mongo：3.11.0
    restart: always
    privileged: true
    volumes:
      - ./docker/mongo/data/db:/data/db
      - ./docker/mongo/data/configdb:/data/configdb
      - ./docker/mongo/init.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_USERNAME: dbuser
      MONGO_PASSWORD: password
      MONGO_DATABASE: flask_factory
    networks:
      back:
        aliases:
          - mongo

networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
